version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - qdrant_network

  fill:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_base
    command: >
      sh -c "python fill_database.py"
    depends_on:
      - qdrant
    networks:
      - qdrant_network

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_base
    command: >
      sh -c "python main_page.py"
    depends_on:
      - qdrant
    ports:
      - 7860:7860
    networks:
      - qdrant_network
      - frontend_network

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  qdrant_network:
    driver: bridge

  frontend_network:
    driver: bridge
