FROM cnstark/pytorch:2.0.1-py3.10.11-ubuntu22.04

COPY . /app
WORKDIR /app
RUN apt update --allow-insecure-repositories
RUN apt install unzip
RUN pip install -r requirements.txt

# Download data
ADD https://storage.googleapis.com/ads-dataset/subfolder-0.zip ./
ADD https://storage.googleapis.com/ads-dataset/subfolder-1.zip ./
RUN unzip subfolder-0.zip
RUN unzip subfolder-1.zip