search:
  BATCH_SIZE: 32
  model_name: openai/clip-vit-base-patch32
  qdrant_host: qdrant
  qdrant_port: 6333
  collection_name: DEFAULT_COLLECTION
  server_name: 0.0.0.0
  server_port: 7860



hydra:
  job:
    chdir: False
